"""Safe default configuration for SafeDesk."""

from safedesk.utils.constants import (
    DEFAULT_ENVIRONMENT,
    DEFAULT_SECURITY_MODE,
    PROJECT_NAME,
    PROJECT_VERSION,
    SUPPORTED_SECURITY_MODES,
)

DEFAULT_CONFIG = {
    "app": {
        "name": PROJECT_NAME,
        "version": PROJECT_VERSION,
        "environment": DEFAULT_ENVIRONMENT,
        "demo_safe_mode": True,
    },
    "owner_profile": {
        "owner_name": "",
        "owner_email": "",
    },
    "setup": {
        "completed": False,
        "setup_version": 1,
        "completed_at": "",
        "last_updated_at": "",
    },
    "security_mode": {
        "default_mode": DEFAULT_SECURITY_MODE,
        "available_modes": list(SUPPORTED_SECURITY_MODES),
    },
    "feature_flags": {
        "enable_real_email": False,
        "enable_real_shutdown": False,
        "enable_real_lockdown": False,
    },
    "face_recognition": {
        "enabled": False,
        "backend": "planned",
        "liveness_check_enabled": False,
        "minimum_confidence": 0.6,
    },
    "owner_face_registration": {
        "enabled": True,
        "required_samples": 5,
        "camera_index": 0,
        "samples_dir": "data/owner/samples",
        "manifest_path": "data/config/owner_registration_manifest.json",
        "image_format": "jpg",
        "image_quality": 90,
    },
    "owner_recognition": {
        "enabled": True,
        "model_name": "ArcFace",
        "detector_backend": "retinaface",
        "distance_metric": "cosine",
        "align": True,
        "enforce_detection": True,
        "minimum_samples_required": 5,
        "profile_path": "data/config/owner_recognition_profile.json",
        "cache_dir": "data/cache/recognition",
        "demo_threshold": 0.68,
        "uncertain_margin": 0.05,
        "offline_after_model_setup": True,
    },
    "liveness": {
        "enabled": True,
        "challenge_duration_seconds": 8,
        "movement_threshold_ratio": 0.08,
        "minimum_detection_frames": 3,
        "camera_index": 0,
        "demo_only": True,
    },
    "authentication": {
        "password_fallback_enabled": False,
        "panic_code_enabled": False,
        "auth_foundation_enabled": True,
        "demo_only": True,
        "secrets_path": "secrets.local.json",
        "hash_algorithm": "pbkdf2_sha256",
        "pbkdf2_iterations": 390000,
        "minimum_password_length": 8,
        "minimum_panic_code_length": 6,
        "max_unlock_attempts": 3,
        "lockout_seconds": 30,
    },
    "otp": {
        "enabled": False,
        "otp_foundation_enabled": True,
        "demo_only": True,
        "delivery_method": "email",
        "code_length": 6,
        "expires_seconds": 120,
        "max_attempts": 3,
        "resend_limit": 2,
        "resend_cooldown_seconds": 30,
    },
    "email": {
        "smtp_host": "smtp.gmail.com",
        "smtp_port": 587,
        "use_tls": True,
        "timeout_seconds": 15,
        "sender_display_name": "SafeDesk",
        "demo_only": True,
    },
    "threat_levels": {
        "enabled": False,
        "initial_level": 0,
        "max_level": 5,
        "forceful_attempt_threshold": 3,
    },
    "shutdown": {
        "real_shutdown_enabled": False,
        "demo_shutdown_only": True,
        "shutdown_after_threat_level": 5,
        "warning_seconds": 30,
    },
    "lockdown": {
        "real_lockdown_enabled": False,
        "demo_lockdown_only": True,
        "allow_recovery_exit": True,
    },
    "alarm": {
        "enabled": False,
        "volume": 0.5,
        "audio_file": "",
    },
    "logging": {
        "enabled": True,
        "database_path": "data/logs/safedesk.sqlite3",
        "log_level": "INFO",
        "demo_only": True,
        "max_recent_events": 50,
        "retention_days": 30,
    },
    "paths": {
        "owner_data_dir": "data/owner",
        "intruder_data_dir": "data/intruders",
        "logs_dir": "data/logs",
        "cache_dir": "data/cache",
        "config_dir": "data/config",
    },
    "privacy": {
        "store_intruder_images": False,
        "store_owner_images": False,
        "local_only_by_default": True,
        "cloud_sync_enabled": False,
    },
    "ui": {
        "theme": "dark",
        "color_theme": "blue",
        "window_width": 1100,
        "window_height": 700,
        "minimum_width": 900,
        "minimum_height": 600,
        "start_maximized": False,
    },
}
