"""Safe default configuration for SafeDesk."""

from safedesk.utils.constants import (
    DEFAULT_ENVIRONMENT,
    DEFAULT_SECURITY_MODE,
    PROJECT_NAME,
    PROJECT_VERSION,
    SUPPORTED_SECURITY_MODES,
)

DEFAULT_CONFIG = {
    "app": {
        "name": PROJECT_NAME,
        "version": PROJECT_VERSION,
        "environment": DEFAULT_ENVIRONMENT,
        "demo_safe_mode": True,
    },
    "owner_profile": {
        "owner_name": "",
        "owner_email": "",
    },
    "setup": {
        "completed": False,
        "setup_version": 1,
        "completed_at": "",
        "last_updated_at": "",
    },
    "security_mode": {
        "default_mode": DEFAULT_SECURITY_MODE,
        "available_modes": list(SUPPORTED_SECURITY_MODES),
    },
    "app_modes": {
        "default_start_mode": "launch",
        "allow_public_lock_placeholder": True,
        "allow_admin_console_from_launch": True,
    },
    "admin_gate": {
        "enabled": True,
        "foundation_enabled": True,
        "demo_only": True,
        "require_password_if_configured": True,
        "allow_development_continue_if_unconfigured": True,
        "max_attempts": 3,
        "lockout_seconds": 30,
    },
    "background_agent": {
        "enabled": True,
        "foundation_enabled": True,
        "demo_only": True,
        "system_tray_enabled": True,
        "minimize_to_tray": True,
        "close_to_tray": False,
        "allow_exit_from_tray": True,
        "show_tray_notifications": False,
    },
    "feature_flags": {
        "enable_real_email": False,
        "enable_real_shutdown": False,
        "enable_real_lockdown": False,
    },
    "face_recognition": {
        "enabled": False,
        "backend": "planned",
        "liveness_check_enabled": False,
        "minimum_confidence": 0.6,
    },
    "owner_face_registration": {
        "enabled": True,
        "required_samples": 5,
        "camera_index": 0,
        "samples_dir": "data/owner/samples",
        "manifest_path": "data/config/owner_registration_manifest.json",
        "image_format": "jpg",
        "image_quality": 90,
    },
    "owner_recognition": {
        "enabled": True,
        "model_name": "ArcFace",
        "detector_backend": "retinaface",
        "distance_metric": "cosine",
        "align": True,
        "enforce_detection": True,
        "minimum_samples_required": 5,
        "profile_path": "data/config/owner_recognition_profile.json",
        "cache_dir": "data/cache/recognition",
        "demo_threshold": 0.68,
        "uncertain_margin": 0.05,
        "offline_after_model_setup": True,
    },
    "liveness": {
        "enabled": True,
        "challenge_duration_seconds": 8,
        "movement_threshold_ratio": 0.08,
        "minimum_detection_frames": 3,
        "camera_index": 0,
        "demo_only": True,
    },
    "intruder_detection": {
        "enabled": True,
        "demo_only": True,
        "camera_index": 0,
        "intruder_images_dir": "data/intruders",
        "manifest_path": "data/config/intruder_capture_manifest.json",
        "image_format": "jpg",
        "image_quality": 90,
        "minimum_owner_samples_required": 5,
        "capture_unknown_only": True,
    },
    "authentication": {
        "password_fallback_enabled": False,
        "panic_code_enabled": False,
        "auth_foundation_enabled": True,
        "demo_only": True,
        "secrets_path": "secrets.local.json",
        "hash_algorithm": "pbkdf2_sha256",
        "pbkdf2_iterations": 390000,
        "minimum_password_length": 8,
        "minimum_panic_code_length": 6,
        "max_unlock_attempts": 3,
        "lockout_seconds": 30,
    },
    "recovery_codes": {
        "enabled": True,
        "foundation_enabled": True,
        "demo_only": True,
        "code_count": 5,
        "code_length": 16,
        "allowed_special_characters": "!@#$%^&*()-_=+[]{}?",
        "single_use": True,
    },
    "otp": {
        "enabled": False,
        "otp_foundation_enabled": True,
        "demo_only": True,
        "delivery_method": "email",
        "code_length": 6,
        "expires_seconds": 120,
        "max_attempts": 3,
        "resend_limit": 2,
        "resend_cooldown_seconds": 30,
    },
    "email": {
        "smtp_host": "smtp.gmail.com",
        "smtp_port": 587,
        "use_tls": True,
        "timeout_seconds": 15,
        "sender_display_name": "SafeDesk",
        "demo_only": True,
    },
    "threat_levels": {
        "enabled": False,
        "foundation_enabled": True,
        "demo_only": True,
        "initial_level": 0,
        "max_level": 5,
        "forceful_attempt_threshold": 3,
        "repeated_unknown_threshold": 3,
        "failed_password_threshold": 3,
        "failed_otp_threshold": 3,
        "forced_exit_threshold": 1,
        "state_path": "data/config/threat_state.json",
    },
    "protected_mode": {
        "enabled": False,
        "foundation_enabled": True,
        "demo_only": True,
        "state_path": "data/config/protected_mode_state.json",
        "allow_manual_arm": True,
        "allow_manual_activation": True,
        "allow_manual_recovery": True,
        "link_threat_level_demo": True,
        "activation_candidate_threat_level": 4,
        "shutdown_candidate_threat_level": 5,
    },
    "shutdown": {
        "foundation_enabled": True,
        "real_shutdown_enabled": False,
        "demo_shutdown_only": True,
        "real_shutdown_command_enabled": False,
        "state_path": "data/config/shutdown_state.json",
        "shutdown_after_threat_level": 5,
        "warning_seconds": 30,
        "countdown_seconds": 30,
        "allow_demo_countdown": True,
        "allow_cancel": True,
        "allow_recovery_cancel": True,
        "require_manual_confirmation": True,
        "link_threat_level_demo": True,
        "link_protected_mode_demo": True,
        "allow_guarded_real_shutdown": False,
        "real_shutdown_supported_platforms": ["Windows"],
        "real_shutdown_countdown_seconds": 60,
        "allow_abort_real_shutdown": True,
        "real_shutdown_requires_confirmation_phrase": True,
        "real_shutdown_confirmation_phrase": "SHUT DOWN SAFEDESK TEST",
    },
    "lockdown": {
        "real_lockdown_enabled": False,
        "demo_lockdown_only": True,
        "allow_recovery_exit": True,
    },
    "alarm": {
        "enabled": False,
        "volume": 0.5,
        "audio_file": "",
    },
    "logging": {
        "enabled": True,
        "database_path": "data/logs/safedesk.sqlite3",
        "log_level": "INFO",
        "demo_only": True,
        "max_recent_events": 50,
        "retention_days": 30,
    },
    "paths": {
        "owner_data_dir": "data/owner",
        "intruder_data_dir": "data/intruders",
        "logs_dir": "data/logs",
        "cache_dir": "data/cache",
        "config_dir": "data/config",
    },
    "privacy": {
        "store_intruder_images": False,
        "store_owner_images": False,
        "local_only_by_default": True,
        "cloud_sync_enabled": False,
    },
    "ui": {
        "theme": "dark",
        "color_theme": "blue",
        "window_width": 1100,
        "window_height": 700,
        "minimum_width": 900,
        "minimum_height": 600,
        "start_maximized": False,
    },
}
