"""Project-wide constants for SafeDesk."""

PROJECT_NAME = "SafeDesk"
PROJECT_VERSION = "1.0.0"

DEFAULT_ENVIRONMENT = "development"
SUPPORTED_ENVIRONMENTS = ("development", "testing", "production")

DEFAULT_SECURITY_MODE = "demo_safe"
SUPPORTED_SECURITY_MODES = ("standard", "strict", "silent_evidence", "demo_safe")

CONFIG_EXAMPLE_FILENAME = "config.example.json"
LOCAL_CONFIG_FILENAME = "config.local.json"
ENV_FILENAME = ".env"

DATA_DIRNAME = "data"
OWNER_DATA_DIRNAME = "owner"
INTRUDER_DATA_DIRNAME = "intruders"
LOGS_DATA_DIRNAME = "logs"
CACHE_DATA_DIRNAME = "cache"
CONFIG_DATA_DIRNAME = "config"

ENV_SAFEDESK_ENV = "SAFEDESK_ENV"
ENV_EMAIL_SENDER_ADDRESS = "SAFEDESK_EMAIL_SENDER_ADDRESS"
ENV_EMAIL_APP_PASSWORD = "SAFEDESK_EMAIL_APP_PASSWORD"
ENV_OTP_RECEIVER_EMAIL = "SAFEDESK_OTP_RECEIVER_EMAIL"
ENV_ENABLE_REAL_EMAIL = "SAFEDESK_ENABLE_REAL_EMAIL"
ENV_ENABLE_REAL_SHUTDOWN = "ENABLE_REAL_SHUTDOWN"
ENV_ENABLE_REAL_LOCKDOWN = "ENABLE_REAL_LOCKDOWN"

LEGACY_ENV_EMAIL_SENDER_ADDRESS = "EMAIL_SENDER_ADDRESS"
LEGACY_ENV_EMAIL_APP_PASSWORD = "EMAIL_APP_PASSWORD"
LEGACY_ENV_OTP_RECEIVER_EMAIL = "OTP_RECEIVER_EMAIL"
LEGACY_ENV_ENABLE_REAL_EMAIL = "ENABLE_REAL_EMAIL"

SECRET_ENV_KEYS = (
    ENV_EMAIL_APP_PASSWORD,
    LEGACY_ENV_EMAIL_APP_PASSWORD,
)
